<h1>Términos y condiciones para afiliados a Sueños de Vida</h1>

<p>
    1. El presente documento describe los Términos y Condiciones aplicables al uso de los servicios que (en adelante, Sueños de Vida o La Empresa), como titular del Sitio, brinda bajo el dominio <b>https://www.suenosdevidacr.com</b>. Se deja expresa constancia que estos Términos y Condiciones regulan los parámetros que brindan la posibilidad de conocer y acceder al sistema de Sueños de vida.</p>

<p>2. Este Acuerdo entra en vigencia a partir de la fecha de aceptación por parte de la Empresa. La Empresa deberá recibir una copia impresa original o una copia enviada por email de este Acuerdo dentro de los treinta (30) días posteriores a mi afiliación para convertirme oficialmente en un Miembro de Sueños de Vida. En caso que la Empresa no reciba copia impresa original o una copia enviada por email de este Acuerdo de mi parte, comprendo que este Acuerdo será tenido como no celebrado. Acepto que la Empresa considere como original mi firma en mi Solicitud en línea, o en mi Solicitud enviada impresa o por e-mail para todos los efectos del presente contrato </p>

<p>3. Una vez aceptada esta solicitud, entiendo que me convertiré en miembro de Sueños de vida y que seré elegible para participar en las promociones de la Empresa y para recibir comisiones residuales generadas por la incorporación a mi red de nuevos miembros, debidamente formalizados, en conformidad con las Normas y Procedimientos y el reglamento de la Empresa. </p>

<p> 4. El Reglamento, normas y procedimientos de uso de la membresía y el plan de ayuda de Sueños de Vida se incorporan por referencia a los términos y condiciones de este Acuerdo, en su forma actual y según sean modificados por Sueños de Vida a su sola discreción. Según se usa a lo largo de este documento, el término Acuerdo se refiere a esta Solicitud y Contrato del Miembro las Normas y Procedimientos y el Reglamento del plan de ayuda de Sueños de Vida. </p>

<p> 5. Entiendo que como miembro soy un contratista; no un agente, empleado o propietario de una franquicia de la Empresa. <b>POR TANTO ENTIENDO Y ACUERDO QUE NO SERE TRATADO COMO EMPLEADO DE Sueños de Vida PARA EFECTOS TRIBUTARIOS o laborales</b>, ni seré tratado como empleado para propósitos de la Ley Orgánica del Ministerio de trabajo ni para efectos del Código de Trabajo. Entiendo y acuerdo que pagaré todos los impuestos aplicables, para quienes trabajan por cuenta propia, impuestos de ventas, impuestos sobre la renta que me corresponda pagar a consecuencia de mis actividades bajo este acuerdo. </p>

<p> 6. Entiendo y acuerdo que mi remuneración consistirá únicamente en comisiones y/o bonificaciones por el patrocinio de miembros a mi red de Sueños de Vida. </p>

<p> 7. Acuerdo que como miembro realizaré mis actividades en forma legal, ética y moral y que haré todo esfuerzo para promover la afiliación de nuevos miembros a la Empresa. Entiendo que como miembro mi conducta debe estar en armonía con el interés público y que evitaré toda práctica descortés, engañosa, falsa o falta de ética. Además, acuerdo obedecer todas las leyes estatales y locales que rijan las operaciones de mi negocio de Sueños de Vida. </p>

<p> 8. Entiendo que no se me garantiza ningún ingreso permanente, ni se me asegura ninguna utilidad o éxito. Soy libre para fijar mi propio horario y para determinar mi propia forma de desarrollar mi red de afiliados, dentro de las directrices y requisitos de este Acuerdo y normas de Ética establecidas por la empresa. Soy responsable de mis propios gastos comerciales en conexión con mis actividades como afiliado. Certifico que ni la Empresa, ni mi patrocinador han hecho afirmación alguna de ganancias garantizadas ni representaciones de ganancias esperadas que podrían ser el resultado de mis esfuerzos como Afiliado. Entiendo que mi éxito como afiliado dependerá del desarrollo de una red de afiliados. Entiendo y acuerdo que no haré declaraciones, divulgaciones o representaciones al ofrecer o al patrocinar a otros posibles Afiliados, que no sea aquella que se encuentren aprobada por la Empresa.</p>

<p> 9. Si patrocino a otros miembros, acuerdo asumir el compromiso y las funciones de supervisión y capacitación de mi red de afiliados. Por lo tanto si un miembro de mi red aplicando el plan de ayuda se retira de la empresa, las ganancias obtenidas por este miembro se me deducirán mensualmente como me fueron asignadas, ya que la empresa entraría en la obligación de efectuar la devolución del dinero invertido por este miembro.</p>

<p> 10. Entiendo y acuerdo que la Empresa puede hacer modificaciones al Acuerdo a su sola discreción, y que todos esos cambios tendrán carácter obligatorio sobre mi persona. Siempre y cuando esos cambios no modifiquen los montos correspondientes a membresía y comisiones que reciben los miembros. Todos los cambios al Acuerdo entrarán en vigor una vez publicados oficialmente por la Empresa. </p>

<p> 11. Los Afiliados no pueden ceder ningún derecho ni delegar ningún deber originado bajo este Acuerdo sin el previo consentimiento escrito de la Compañía. Toda cesión o delegación no autorizada podrá ser anulada a opción de la Empresa. </p>

<p>12. El término de este Acuerdo es de tres (3) año. Después de la finalización del presente contrato, el Afiliado, se compromete a no revelar a terceros información comercial ni material informativo que el Afiliado haya conocido durante la vigencia del presente contrato, Yo podré renunciar a este acuerdo en el momento que lo notifique por escrito o por medios electrónicos a la Empresa. </p>

<p>13. Las partes renuncian a todos sus derechos, a daños incidentales, indirectos, de carácter ejemplar y punitivo que se originen en cualquier violación del Acuerdo. Toda renuncia o abandono de un derecho con relación a cualquier violación de este Acuerdo deberá ser por escrito y ser firmado por una persona autorizada. La renuncia o abandono de un derecho de parte de Sueños de Vida con relación a cualquier violación de este Acuerdo por mi persona no tendrá efecto ni deberá interpretarse como renuncia o abandono de derechos relacionados con violaciones posteriores.
</p>

<p>14. Todos los demás asuntos relacionados con este Acuerdo serán regidos por las leyes Costa Rica. Las partes acuerdan que la jurisdicción y competencia territorial para cualquier asunto se hará en los juzgados estatales. Este Acuerdo tendrá carácter de obligatoriedad sobre los sucesores y asignatarios de ambas partes. </p>

<p>15. Acepto que seré sujeto a las sanciones disciplinarias que se especifiquen en las Normas y Procedimientos de Sueños de Vida a discreción de la Empresa por la violación o desacato de cualquier término o disposición del Acuerdo. Una vez cancelado voluntaria o involuntariamente este Acuerdo, perderé, y renuncio expresamente, a cualquiera y todos los derechos, incluso los derechos de propiedad, sobre mi organización en línea descendente previa y a cualquier bonificación, comisión u otra compensación que resulten por mí mismo o por mi organización en línea descendente previa. </p>

<p> 16. Certifico que el número que aparece en este formulario es mi número de CEDULA También ratifico y acepto que mi domicilio y demás datos particulares son los que aparecen en el presente documento. todos los datos con los que he llenado este formulario son correctos y reales y acepto de que en caso de que la empresa compruebe lo contrario procederá a la cancelación absoluta e inmediata de mi afiliación a Sueños de Vida, perdiendo todos mis derechos y manteniendo todas mis obligaciones ante las autoridades en caso de ser necesario.</p>

<p>17. Una vez Pre-registrado el afiliado mediante su afiliación online y recibida la correspondiente cuota de Afiliación, recibirá un nombre de Usuario ID y se le activará de forma provisional su licencia de usuario, quedando ésta condicionada a la recepción por parte de Sueños de Vida del presente Contrato debidamente firmado en todas sus páginas, y acompañado por una copia del documento de identidad del afiliado, en el caso de que en el transcurso de 30 días posteriores al pago de la afiliación Sueños de Vida no hubiese recibido dicho contrato y documentación, se cancelará el uso de la licencia correspondiente a dicho usuario por presumir la desidia del mismo en el desarrollo del negocio.</p>
<p>18. La Empresa tendrá derecho a deducir y a compensar con mis comisiones, o cualquier otro dinero que me deba pagar, las membrecía mensual, o cualquier otro dinero que el miembro adeude a la Compañía.

</p>
<p> 19. Bajo pena de perjurio, certifico que he estudiado y entendido la información que se encuentra en este formulario y sus anexos y que según mi entendimiento y opinión es verdadera, correcta y completa. Doy fe, además y bajo pena de perjurio de que: Soy el beneficiario de todos datos Ingresados y declarados en este formulario. y acuerdo cumplir y estar sujeto a los términos y condiciones que contienen. </p>

<p> <b>TERMINOS Y CONDICIONES --- CONTRATO DE MIEMBROS SUEÑOS DE VIDA  <br/>
        Gerencia General Sueños de vida CR S.A</b>

</p>